version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - data:/app/data
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev

  cron:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - data:/app/data
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run cron

volumes:
  data: 