services:
  # Web service
  - type: web
    name: scholar-embed
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERPAPI_KEY
        sync: false
      - key: GOOGLE_SCHOLAR_URL
        sync: false

  # Cron job
  - type: cron
    name: update-publications
    runtime: node
    schedule: "0 0 * * *"  # Run at midnight every day
    command: node src/cron/update-publications.js  # Direct command to run the script